### ISSUE TITLE
dash in schema name

### ISSUE THREAD

**Issue by shoaib-iqbal** [ramontayag/storey#39]
Hi i have multi domain site with apartment gem,i which a sub domain can be dash-test.com,when a switch a schema with this gem it omit dash from name and make a schema with first name?
Is there any way do this?

**Comment by ramontayag** [comment]
@shoaib-iqbal I [wondered the same thing before](http://dba.stackexchange.com/a/45591/25592). In short, you can't have a dash in the schema name.

**Comment by ramontayag** [comment]
I'll close this. You may open if you have other questions.
